version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "3306:3306"
    volumes:
      - my_db_data:/var/lib/mysql

volumes:
  my_db_data:
